CREATE DATABASE DB_NAME;

CREATE USER 'DB_USER'@'DB_HOST' IDENTIFIED WITH mysql_native_password BY 'DB_PASSWORD';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, INDEX, DROP, ALTER, REFERENCES, CREATE TEMPORARY TABLES, LOCK TABLES ON DB_NAME.* TO 'DB_USER'@'DB_HOST';
GRANT SELECT, CREATE VIEW, SHOW VIEW, LOCK TABLES, EVENT, TRIGGER ON DB_NAME.* TO 'DB_USER'@'DB_HOST';
-- privileges for mysqldump command
GRANT FILE, RELOAD, REPLICATION CLIENT, SESSION_VARIABLES_ADMIN, SYSTEM_VARIABLES_ADMIN ON *.* TO 'DB_USER'@'DB_HOST';

FLUSH PRIVILEGES;
